image:
  repository: harbor.devopsviet.io.vn/hoatranlab/hoa-hello
  pullPolicy: IfNotPresent
  tag: "latest" # Pipeline sẽ sửa dòng này

# Secret tạo ở bước 0.3
imagePullSecrets:
  - name: harbor-creds

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: nlb.hoatranlab.io.vn
      paths:
        - path: /
          pathType: Prefix
