image:
  repository: harbor.devopsviet.io.vn/hoatranlab/hoa-hello
  pullPolicy: Always
  tag: "latest" # CI sẽ update dòng này

# Secret tạo ở bước 0.2
imagePullSecrets:
  - name: harbor-creds

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: nlb.hoatranlab.io.vn
      paths:
        - path: /
          pathType: Prefix